# Generated by Django 4.1 on 2022-08-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_studentdetails_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='joining_date',
            new_name='joiningDate',
        ),
    ]
