# Generated by Django 4.1 on 2022-08-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_rename_joining_date_studentdetails_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='joiningDate',
            field=models.DateField(null=True),
        ),
    ]
