# Generated by Django 4.1 on 2022-08-28 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_alter_studentdetails_joiningdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='joiningDate',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
