# Generated by Django 3.2.5 on 2022-08-28 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_remove_studentdetails_joiningdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
