# Generated by Django 4.1 on 2022-08-29 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_alter_studentdetails_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=True),
            preserve_default=False,
        ),
    ]
